### ISSUE TITLE
[Closed for inactivity] Don't work

### ISSUE THREAD

**Issue by Saber-Tooth-Tiger** [ProdigyPNP/ProdigyMathGameHacking#102]
### Describe the bug

So, I am on a macbook air, but my operating system is windows 10, and I wanted to downlowd hack and compress the zip file,and after compressing the file, I tried to load is on my chrome extension with the developer mode, but it keeps sending me errors! Also btw I tried the same thing on my other completely windows computer and it worked well, but don't know why is it doing this now? :( Plz help! :( Thanks! :)

### Describe how to replicate bug

I compress the downlowd file and load it, it will show the error again

### Date of submittion

2022. 7. 13

### Your PHEx version

Not even installed yet, cause I am not able to :(

### Your operating system and the version

my operating system is wondows 10

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by Erisfiregamer1** [comment]
Try unzipping it, clicking "Load Unpacked" and clicking the folder you extracted it in.
*There should be .js files in the folder, if not something's wrong.*

**Comment by Erisfiregamer1** [comment]
Did it work @Saber-Tooth-Tiger ? If I get no response I'm closing.

**Comment by Saber-Tooth-Tiger** [comment]
oh sry for not replying was busy all week long, it worked though!! thanks!

**Comment by Saber-Tooth-Tiger** [comment]
sorry for no replying it didn't work but can you get me the page where it
shows how to update prodigy hacking extension, cause i think that zip file
might work! thanks! :)

**Comment by afkvido** [comment]
Do you mean this? https://github.com/ProdigyPNP/ProdigyMathGameHacking/blob/master/meta/wiki/UPDATING.md

**Comment by Erisfiregamer1** [comment]
Closed as completed (User's issue solved)

**Comment by afkvido** [comment]
Closed as not planned cuz I don't believe it's a bug with the hacks. Completed = Tracking issues, feature requests, legitamente bugs. 

this is just a support req

**Comment by Saber-Tooth-Tiger** [comment]
yes thanks! But still no work! I got the antivirus, maybe its because there
is virus in the zip

**Comment by afkvido** [comment]
Bruh there's no virus anywhere, take a look at our code.

**Comment by afkvido** [comment]
@Saber-Tooth-Tiger "sus"? Are you retarded? Read our code moron.
