### ISSUE TITLE
[HR] Prodigy ELA Scam

### ISSUE THREAD

**Issue by jat354155** [ProdigyPNP/ProdigyMathGameHacking#133]
### Describe the hack

Why doesn't PMGH not have the free membership feature for ELA, I find the membership to be a scam, because it is a clear Animal Crossing rip-off. Please add an ELA hack gui!

### Date of submittion

8/9/2022

### Before submitting a hack request

- [X] This hack wasn't already requested.
(I have checked every hack request on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
I believe that this is a Prodigy English hack request. We're not onto hacking Prodigy English **yet**. Stay up to date on our GitHub Discussions and our Discord for updates.

**Comment by Natedogwoooof** [comment]
prodigy rips off Nintendo how do i know i play prodigey and i own a swich and 3DS

**Comment by afkvido** [comment]
lmao
