### ISSUE TITLE
[O] Prodigy Math Multirequest

### ISSUE THREAD

**Issue by jat354155** [ProdigyPNP/ProdigyMathGameHacking#134]
### Describe your issue

The Prodigy Math Membership hack gives what seems to be basic membership, which causes the popups to go away, but where is the ultimate membership?

While I was away from posting "complaints"(get it, issues... LOL), I thought of the unobtainable epic morphs, specifically the "follow" variants of them, I remembered they make your wizard invisible, maybe this could have its own button? (I have an alt in which I have challenged myself to only use pets [I made my wizard invisible for the haha funny]) **You don't really need to change anything here as it's fine anyways, but it'd be nice for them to have their own unique menu.**

After typing the last bit that second paragraph, why can't we just remove the wizard altogether? What's wrong with NOT having an astral type on your team?.. Or adding another one :trollface:.

- [ ] #135
- [ ] Make "follow" Epics unique from other morphs **Optional**
- [ ] #136

### Date of submittion

8/9/2022

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
>  Ultimate Membership
We're gonna do that soonTM

**Comment by afkvido** [comment]
> Make "follow" Epics unique from other morphs

might consider it

**Comment by afkvido** [comment]
> Ability to remove/add more wizard(s)

Ho there! I'm not sure if it's possible, but I'll take a look.

**Comment by afkvido** [comment]
Also, since I've opened individual issues for these, I'll close this big multirequest.
