### ISSUE TITLE
[HR] WASD Controls

### ISSUE THREAD

**Issue by jat354155** [ProdigyPNP/ProdigyMathGameHacking#137]
### Describe the hack

I remember seeing on the fandom wiki a poll asking what controls people wanted added to prodigy, the greasyfork page for it is deleted, and I was mad to not see my character moving with WASD,
I wonder if you could add such controls to prodigy...

### Date of submittion

8/10/2022

### Before submitting a hack request

- [X] This hack wasn't already requested.
(I have checked every hack request on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by Erisfiregamer1** [comment]
Can't be too bad. Just check if there's a wall in the way, and if not teleport the player in a direction every frame slightly in the direction they are holding.

**Comment by afkvido** [comment]
Even better: let us phase through walls :)

**Comment by jat354155** [comment]
Idea: Wall phasing could have its own hack, that is affected if this one in enabled

**Comment by afkvido** [comment]
ehhh idk

**Comment by afkvido** [comment]
> Idea: Wall phasing **could** have its own hack, that has an effect on **this one** if it is enabled

That part is done... now we need to implement the non-phasing hack

**Comment by afkvido** [comment]
Found smth! 
```js
MouseEvent
PointerEvent
```

**Comment by afkvido** [comment]
Complete. Though, it's phasing only for now.
