### ISSUE TITLE
LOOKING FOR COLLABORATORS

### ISSUE THREAD

**Issue by afkvido** [ProdigyPNP/ProdigyMathGameHacking#149]
If you know your way around Prodigy's objects, and can do some TypeScript, please, comment on this issue so I can invite you to help out.

**Prerequisites:**
- at least 1 useful PR on this repo, (or P-NP, or infinitezero, etc.)
- Some knowledge of TypeScript
- You've taken a look at our repos: ProdigyMathGameHacking (see the PHEx and cheatGUI folders), P-NP (our gamefile patcher), and InfiniteZero (a load balancer of sorts, kindof).

**What you will learn by joining us:**
- Prodigy's objects
- Our development process
- Inner workings of ProdigyPNP

**Comment by ProdigyPNPEnthusiast** [comment]
Could I become a collabortator?

**Comment by afkvido** [comment]
@ProdigyPNPEnthusiast After your PR for P-NP, I think you're a pretty good fit. However, as your account was created 11 hours ago, I'm still suspicious if you're someone like Eris or Hosted.

If you're not, I'm genuinely sorry, I just have no way of knowing. I'll make sure to check out all PRs you make tho, for the time being.

**Comment by ProdigyPNPEnthusiast** [comment]
How's Hosted?

**Comment by afkvido** [comment]
The owner of ProdigyX.

**Comment by ProdigyPNPEnthusiast** [comment]
> If you're not, I'm genuinely sorry, I just have no way of knowing. I'll make sure to check out all PRs you make tho, for the time being.

My teacher told us in class that if we made a repo/or got a collaborator in a repo with at least 10 stars we will get extra credit. So I'll do my best to prove to you I'm not one of them.

**Comment by ProdigyPNPEnthusiast** [comment]
What if we added a disable collision hack?

**Comment by afkvido** [comment]
> What if we added a disable collision hack?

For WASD?

**Comment by afkvido** [comment]
> My teacher told us in class that if we made a repo/or got a collaborator in a repo with at least 10 stars we will get extra credit. So I'll do my best to prove to you I'm not one of them.

thanks.

**Comment by ProdigyPNPEnthusiast** [comment]
In general.

**Comment by afkvido** [comment]
> In general.

Wdym by "disable collision" then?

**Comment by ProdigyPNPEnthusiast** [comment]
walking through walls

**Comment by afkvido** [comment]
Ah. Our WASD hack lets you walk through walls.

**Comment by afkvido** [comment]
So it already exists i guess

**Comment by afkvido** [comment]
But in general

**Comment by afkvido** [comment]
You mean, to add it to click movement too?

**Comment by ProdigyPNPEnthusiast** [comment]
yeah

**Comment by ProdigyPNPEnthusiast** [comment]
I think I found something

**Comment by ProdigyPNPEnthusiast** [comment]
when I run ``_.player._playerContainer.locomotion.screen.area = _.player._playerContainer.locomotion.screen.area.map(e => e.fill(1))`` I can click on walls and walk on them

**Comment by afkvido** [comment]
That does work :)

**Comment by ProdigyPNPEnthusiast** [comment]
The teacher will give out the extra credit Friday, although she said the first person to get it gets 10 additional points instead of 5.

**Comment by ProdigyPNPEnthusiast** [comment]
> @ProdigyPNPEnthusiast After your PR for P-NP, I think you're a pretty good fit. However, as your account was created 11 hours ago, I'm still suspicious if you're someone like Eris or Hosted.

My teacher said it has to be done on a new account as you could have already reached it. So she had us make new ones in class.

**Comment by ProdigyPNPEnthusiast** [comment]
Should I make a pr?

**Comment by afkvido** [comment]
> Should I make a pr?

Yes please.

**Comment by afkvido** [comment]
> > @ProdigyPNPEnthusiast After your PR for P-NP, I think you're a pretty good fit. However, as your account was created 11 hours ago, I'm still suspicious if you're someone like Eris or Hosted.
> 
> My teacher said it has to be done on a new account as you could have already reached it. So she had us make new ones in class.

Ooooo whats ur main acc then?

**Comment by afkvido** [comment]
> The teacher will give out the extra credit Friday, although she said the first person to get it gets 10 additional points instead of 5.

Cool! are you the first?

**Comment by ProdigyPNPEnthusiast** [comment]
I'm not a collaborator yet.

**Comment by afkvido** [comment]
Oh. You sure she didn't mean contributor?

**Comment by ProdigyPNPEnthusiast** [comment]
Aren't they interchangable?

**Comment by afkvido** [comment]
Collaborator means that you have a certain access level, like push to non-master branch.

Contributor means that you've made a contribution to the repo, usually a PR that got merged.

**Comment by ProdigyPNPEnthusiast** [comment]
I made the pr

**Comment by ProdigyPNPEnthusiast** [comment]
> > > @ProdigyPNPEnthusiast After your PR for P-NP, I think you're a pretty good fit. However, as your account was created 11 hours ago, I'm still suspicious if you're someone like Eris or Hosted.
> > 
> > 
> > My teacher said it has to be done on a new account as you could have already reached it. So she had us make new ones in class.
> 
> Ooooo whats ur main acc then?

@MattTheEditor I have not done much on GitHub.

**Comment by MattTheEditor** [comment]
Here's proof.

**Comment by afkvido** [comment]
Huh. That's like nothing on that acc lmao but ok

**Comment by ProdigyPNPEnthusiast** [comment]
Well it proves I'm not Hosted or Eris

**Comment by afkvido** [comment]
Not really lol hosted/eris could still own all those accounts so yea :\

Tho u did get contributor on the repo. Were you the first?

**Comment by ProdigyPNPEnthusiast** [comment]
yep.

**Comment by afkvido** [comment]
Nice!

**Comment by Erisfiregamer1** [comment]
I'm going to put this out now: I own neither @ProdigyPNPEnthusiast or @MattTheEditor . I have no desire to associate with this repo further.

**Comment by afkvido** [comment]
@Erisfiregamer1 Ain't associating with this repo, ain't you?
Then what's https://github.com/Eris-Webservices/ProdigyMathGameHacking

**Comment by hostedposted** [comment]
> Not really lol hosted/eris could still own all those accounts so yea :\

Similar to Eris I don't own, either of those accounts. It is against github's rules to own multiple accounts. Also if I wanted to make this hack end, I would simply write a script to DDoS you. If Prodigy can do it, then I can too.

**Comment by afkvido** [comment]
Thought you already wrote a script to DDoS me. Ain't your twos' presence here a bit suspicous.

**Comment by AgrTheDev** [comment]
tfym two

**Comment by Erisfiregamer1** [comment]
> Thought you already wrote a script to DDoS me. Ain't your twos' presence here a bit suspicous.

I'm here because I was just browsin through Github and saw what you said.
Oh, BTW, the repos are gone. Go check.

**Comment by afkvido** [comment]
> tfym two

twos' was reffering to @Erisfiregamer1 and @hostedposted

**Comment by afkvido** [comment]
> I'm here because I was just browsin through Github and saw what you said. Oh, BTW, the repos are gone. Go check.

@Erisfiregamer1 The repos are gone, or at least privated. That much I can confirm.

**Comment by Erisfiregamer1** [comment]
That was from a while back. Once I get back from my classes (they block Github), I'll be removing them.

Please note that I'm on the ProdigyX team now. I really don't want to do anything to help or harm this repo; I just want to further the Prodigy hacking scene.
------- Original Message -------

**Comment by afkvido** [comment]
I know all that lol

**Comment by afkvido** [comment]
But thanks anyways for being part of ProdigyPNP while you were.

**Comment by Erisfiregamer1** [comment]
Thanks.
