### ISSUE TITLE
[B] Cheat Menu always loads from a static URL.

### ISSUE THREAD

**Issue by afkvido** [ProdigyPNP/ProdigyMathGameHacking#15]
## Actual Behavior
Cheat Menu always loads from a static URL.

## Expected Behavior
Cheat Menu will load from the URL specified in P-NP. At ProdigyPNP/P-NP/[dist/util.js](https://github.com/ProdigyPNP/P-NP/blob/main/dist/util.js), line 18 and 19.

## Location
At ProdigyPNP/ProdigyMathGameHacking/[willsCheatMenu/src/hacks/utility.ts](https://github.com/ProdigyPNP/ProdigyMathGameHacking/blob/a8d6e4d6cc75eca1e799042e219c86899b84c45f/willsCheatMenu/src/hacks/utility.ts), line 91.

# I know the fix
In P-NP, add another URL export at `[pnpDomain]/cheatmenu`.

<br><br>

In ProdigyMathGameHacking, load the cheat menu like this:

javascript:
```js


const cmu = // get the cheat menu URL from [pnpDomain]/cheatmenu

(async () => {
		eval(await (await fetch(`${cmu}?updated=${Date.now()}`)).text()); // updated parameter is so browser ignores cached version
	})();
```

**Comment by Erisfiregamer1** [comment]
Status on this?

**Comment by afkvido** [comment]
In theory, P-NP decides which cheat menu to load... however if someone is trying to use our cheat menu (cheatGUI) but it's self-hosted, that _should_ be their issue.

However, I believe that the fix is to append a line of code in the P-NP output (game.min.js) which says something like:

```js
const PNPURL = "https://p-np.prodigypnp.repl.co";
```

Then, we can substitute the line in Update Menu to load from PNPURL.
