### ISSUE TITLE
[O] Server

### ISSUE THREAD

**Issue by yeeteeyt** [ProdigyPNP/ProdigyMathGameHacking#154]
### Describe your issue

Heyyyy, vido, wondering if you could perhaps make a server for my previous repo (cavegame), thank you very much

### Date of submittion

today duh

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
This isn't an issue for ProdigyMathGameHacking. Ask me on Discord if u can.

also ye i remember u
