### ISSUE TITLE
Can't for some reason do it on school chromebook

### ISSUE THREAD

**Issue by helloeveryonehoware** [ProdigyPNP/ProdigyMathGameHacking#159]
### Describe your issue

When I try getting it on the webstore it gets blocked on the chromebook and I can do a manual installation because it's disabled

### Date of submittion

9/15/22

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Alright, I'm not really sure how to help with that, but some hacks are possible without the extension.

Open DevTools, and then the JavaScript console. Paste this line of code in (This sets your gold to 1000000). If you want any other hacks than gold, tell me, I'll see if I can get them to work without the extension.

```js
Boot.prototype.game._state._current.user.source.data.gold=1000000;
```
