### ISSUE TITLE
[BUG] You can't do the dark tower with teleport to click enabled

### ISSUE THREAD

**Issue by iBstoopid** [ProdigyPNP/ProdigyMathGameHacking#161]
### Describe the bug

You can't go to level 2 with tp2click enabled

### Describe how to replicate bug

enable tp to click beat a level and try to go in the door

### Date of submittion

9/15/22

### Your PHEx version

latest

### Your operating system and the version

windows 10 lastest chrome

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Sorry, low priority because this is situational and rare.

**Comment by afkvido** [comment]
This is definitely a problem on your end, not the hacks. I have tested this, and the toggle click teleporting doesn't cause any problems in the dark tower.
