### ISSUE TITLE
Kennel does nothing

### ISSUE THREAD

**Issue by helloeveryonehoware** [ProdigyPNP/ProdigyMathGameHacking#165]
### Describe the bug

Kennel doesn't change the ui or do anything like that it just is there

### Describe how to replicate bug

Just click on switch branch>then kennel

### Date of submittion

9/19/2022

### Your PHEx version

3.0.1

### Your operating system and the version

PC Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
If you don't know what Switch Branch is for, don't use it.

Switch Branch is for development, not just users. The kennel branch is something we're developing.
