### ISSUE TITLE
[O] Possible Malware

### ISSUE THREAD

**Issue by GodlyGavin1** [ProdigyPNP/ProdigyMathGameHacking#166]
### Describe your issue

My anti virus says that its dangerous, but all my other ones don't say anything. I've used it before but it never said anything about malware or viruses. Its either something in the code or a bug on my side.

### Date of submittion

9-19-2022

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Definitely a bug on your side. All ProdigyPNP software is open source, meaning you can read the code to it if you'd like to. 

If an antivirus is pissed, it's probably because we're using scripts from our servers that we load into Prodigy to make it hackable.

What's your OS and browser?

**Comment by GodlyGavin1** [comment]
I'm using an old mac and google chrome. You can see the picture for my Mac info.
<img width="587" alt="Screen Shot 2022-09-20 at 5 50 36 PM" src="https://user-images.githubusercontent.com/78817291/191371303-c8e55d12-e851-4423-a369-69d18a2383fd.png">

**Comment by GodlyGavin1** [comment]
I think my anti virus thinks its malware because it messes with the prodigy website a bit.

**Comment by afkvido** [comment]
> I'm using an old mac and google chrome. You can see the picture for my Mac info. 

damn thats a bit old

**Comment by afkvido** [comment]
> I think my anti virus thinks its malware because it messes with the prodigy website a bit.

lmao it's not a virus take a look at our code

**Comment by GodlyGavin1** [comment]
I know its not a virus, my anti-virus is just acting up

**Comment by afkvido** [comment]
alr alr
