### ISSUE TITLE
[O] Blocked

### ISSUE THREAD

**Issue by UsernameWasInvalid** [ProdigyPNP/ProdigyMathGameHacking#169]
My admin has chrome store blocked and you can't download extensions along with downloads being blocked from github, Are there any alternatives to prodigy cheats?

**Comment by afkvido** [comment]
Follow the steps in https://github.com/ProdigyPNP/ProdigyMathGameHacking/blob/master/meta/manual/CHROME.md

## HOWVER, IN STEP 6, INSTEAD OF DOWNLADING PHEx.ZIP FROM GITHUB: DOWNLOAD IT FROM HERE: 
### https://starfiles.co/file/6c497a1bf7f0/PHEx-3-0-1-zip

**Comment by afkvido** [comment]
@UsernameWasInvalid Will the Direct URL work? https://api.starfiles.co/direct/6c497a1bf7f0

**Comment by UsernameWasInvalid** [comment]
Have you tried google drives since my admins filter blocks 98% of downloads from websites and no it does not work and its blocked

**Comment by afkvido** [comment]
Alright i guess does this work? https://drive.google.com/file/d/1Zp8ByR_ZhK8K7rJBBjarZ4quKJxMCrx8/view

**Comment by TheSovietSoldier** [comment]
Its download but once i tried to drag it in to install it wont work it says this:

Failed to load extension from: /tmp/PHEx-3.0.1_VDvBvQ. Loading of unpacked extensions is disabled by the administrator.

**Comment by afkvido** [comment]
Then its blocked on ur computer

**Comment by TheSovietSoldier** [comment]
Well sorry for wasting your time, But one last thing what "hacks" are in the extension anyway? just curious

**Comment by afkvido** [comment]
The extension blocks Prodigy's gamefile and loads ours instead. Ours allows you to load things such as cheatGUI.

**Comment by TheSovietSoldier** [comment]
Does it allow to edit my level, And if it does will it stay on the account

**Comment by afkvido** [comment]
Our gamefile lets you do a lot more than that. I can give you an edit level hack even without the extension if you want.

**Comment by TheSovietSoldier** [comment]
That would be nice since ive been trying to get an extension but no luck so yea

**Comment by afkvido** [comment]
This lets you set your level to anything 100 or below. Using the extension lets u uncap it tho.

```js
function setLevel (lvl) {

    /** player variable */
    const player = Boot.prototype.game._state._current.user.source;

    // TODO implement swal laterTM
    const level = lvl;

    if (level === undefined) return;

    // now we calculate how many stars the level *should* have
    // from 3-16-1.js:8382


    if (level === 1) return 0;

    const i = level - 2;

    // xpConstant from 3-16-1.js:8528

    const xpConstant = 1.042;
    player.data.stars = Math.round((1 - Math.pow(xpConstant, i)) / (1 - xpConstant) * 20 + 10);
    player.data.level = +level;
    player.getLevel = () => {
        return player.data.level;
    };

}

// TODO Implement swal later
setLevel(100);
```

**Comment by TheSovietSoldier** [comment]
Can accounts go past 100

**Comment by afkvido** [comment]
Yes if youre using the extension, but trying to make this go over 100 will be useless

**Comment by TheSovietSoldier** [comment]
Ahh makes sense but even with the extension would it stay

**Comment by afkvido** [comment]
With the extension there's a thing called "Uncap Player Level", but you need the extension **always** whenever you want uncap to function. Otherwise it'll just be 100.

**Comment by TheSovietSoldier** [comment]
Understandable, Oh one last thing is there something to automatically make prodigy accounts
