### ISSUE TITLE
PNP not loading once world

### ISSUE THREAD

**Issue by helloeveryonehoware** [ProdigyPNP/ProdigyMathGameHacking#171]
### Describe the bug

once I load into the world prodigy PNP doesn't load

### Describe how to replicate bug

join prodigy and load into a world

### Date of submittion

9/23/2022

### Your PHEx version

3.0.1

### Your operating system and the version

Windows Education windows 10

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
try again. this is fixed.

**Comment by helloeveryonehoware** [comment]
thank you
