### ISSUE TITLE
Less options for hack

### ISSUE THREAD

**Issue by helloeveryonehoware** [ProdigyPNP/ProdigyMathGameHacking#175]
### Describe the bug

For some reason I don't see as much things to toggle and less beta hacks I'm confused

### Describe how to replicate bug

Join a world then load up the hack and you'll see that there's less options

### Date of submittion

9/26/2022

### Your PHEx version

3.0.1

### Your operating system and the version

Windows 10 education

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Perhaps, you should, y'know, know what you're doing before submitting a bug report? Prodigy broke many of our hacks. So please, KNOW WHAT YOU'RE DOING FFS when submitting a bug report
