### ISSUE TITLE
Where did Toggle Membership hack go?

### ISSUE THREAD

**Issue by Saber-Tooth-Tiger** [ProdigyPNP/ProdigyMathGameHacking#176]
### Describe your issue

Hey there, today i just checked on prodigy again, and i was just checking out the hacks, and then i found out that the 'toggle membership hack' isn't there anymore? Btw i am using the one on the chrome extension, and i refreshed and refreshed, but it just won't show, i even deleted and reintalled the extension, but still does not work, plz respond ASAP :)
Thank you :)

### Date of submittion

sept 27, 2022

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Bro 💀 prodigy broke it. IT WILL BE BACK WHEN WE FIX P-NP.

If you need further help then contact me on the discord https://dsc.gg/prodigypnp
