### ISSUE TITLE
Cannot battle arena

### ISSUE THREAD

**Issue by The-kidAAAAAA** [ProdigyPNP/ProdigyMathGameHacking#183]
### Describe the bug

prodigy just resets the page when you battle in arena

### Describe how to replicate bug

Go to the arena and battle

### Date of submittion

1/10/22

### Your PHEx version

idk probably latest

### Your operating system and the version

Macos Monterey 12

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Write a better issue. This isn't helpful at all.
