### ISSUE TITLE
No menu

### ISSUE THREAD

**Issue by actual-ethan** [ProdigyPNP/ProdigyMathGameHacking#184]
### Describe the bug

After using the extension for no longer then 15 miniutes it suddenly just stopped showing the menu

### Describe how to replicate bug

![image](https://user-images.githubusercontent.com/82302110/194112968-5e211bbf-3818-4b63-8379-d53a59085256.png)

### Date of submittion

10/5/22

### Your PHEx version

idfk

### Your operating system and the version

Windows 11

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by actual-ethan** [comment]
didnt do it right but idgaf

**Comment by actual-ethan** [comment]
and I didnt press shift

**Comment by afkvido** [comment]
Bruh its literally in the top left corner
