### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by helloeveryonehoware** [ProdigyPNP/ProdigyMathGameHacking#187]
### Describe the bug

When you log into prodigy and see the prodigyPNP page the world/game doesn't load idk if this only happens because I'm using it on a school computer

### Describe how to replicate bug

Install PNP>Log in>Wait for the bar to reach the middle

### Date of submittion

10/14/2022

### Your PHEx version

3.0.1

### Your operating system and the version

ProDesk windows 10 EliteDisplay E222

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
This isn't a bug, it's specific to you.

**Comment by afkvido** [comment]
Please send a screenshot of your debug console.
