### ISSUE TITLE
[B] title

### ISSUE THREAD

**Issue by sofia-it837** [ProdigyPNP/ProdigyMathGameHacking#194]
### Describe the bug

gtfgthjnk

### Describe how to replicate bug

hyujk

### Date of submittion

n njjnhbhb

### Your PHEx version

gctfucg.

### Your operating system and the version

 hjbuhb

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by GodlyGavin1** [comment]
****underaged child detected***

**Comment by afkvido** [comment]
Fr
