### ISSUE TITLE
[B] title

### ISSUE THREAD

**Issue by heqds** [ProdigyPNP/ProdigyMathGameHacking#197]
### Describe the bug

When I try to open the hack, I get to the loading screen where it's loading worlds and stuff then it says it is outdated. My version is 3.0.1 and that is the GitHub ver that is newest.

### Describe how to replicate bug

Not sure if it is me or the menu. I load prodigy then I do the screens that say "math or English" and stuff then it says "Loading" and then I get an error that tells me I am outdated.

### Date of submittion

October 30th 2022

### Your PHEx version

3.0.1

### Your operating system and the version

Windows 11 Brave

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Please see #190 for an overarching issue- fixing that will fix this too.
