### ISSUE TITLE
[B] Not up to date, though, it is?

### ISSUE THREAD

**Issue by StormDoesStuff** [ProdigyPNP/ProdigyMathGameHacking#198]
### Describe the bug

Hey! 
When I attempt to sign in to prodigy, PHEx claims my version is the latest, though I downloaded the latest, 3.01, and did it for the browser I use. 
![Screen Shot 2022-11-01 at 7 06 13 AM](https://user-images.githubusercontent.com/105564285/199219984-bd9ec7e6-dc43-4fe4-8754-b95fa04cfdd6.png)
MacOS 10.13.6 is my Mac version, I need to buy a new one, it's too old..

### Describe how to replicate bug

I think it's personal, I don't know.

### Date of submittion

11/1/22

### Your PHEx version

3.01

### Your operating system and the version

MacOS 10.13.6 

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Good bug report, thanks, but currently there is an overarching error of the hacks being patched. Once that is fixed, we will bring hack servers back online. This is due to hacks being offline.
