### ISSUE TITLE
[O] ruining prodigy x

### ISSUE THREAD

**Issue by helloeveryonehoware** [ProdigyPNP/ProdigyMathGameHacking#199]
### Describe your issue

Should I nuke ProdigyX's server or should I not just tell me if you want or don't want since if you do then I need a reason to nuke them though it shouldn't be hard to find one but I also need a reason to not nuke prodigy x's server.

A way to reach me:

Discord: Jack_from_doors#9003

### Date of submittion

11/1/2022

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by helloeveryonehoware** [comment]
But watch out prodigy x devs since there's lots of nukers.

**Comment by afkvido** [comment]
Bro 💀 Prodigy X nuked my ProdigyPNP server once.

**Comment by afkvido** [comment]
We should mass report Prodigy X's server tho because if my server was TOS'd, then it's only fair that the people who hack Prodigy **for profit** should also suffer.

**Comment by helloeveryonehoware** [comment]
alr

**Comment by helloeveryonehoware** [comment]
@afkvido Imma see if there's a nuker that doesn't need you to have higher perms in a server to nuke alr and ima search on youtube and github

**Comment by afkvido** [comment]
don't bother tbh

**Comment by afkvido** [comment]
prodigypnp is dead. soon i'm going to make an announcement before i archive this repo.
