### ISSUE TITLE
How to Donate

### ISSUE THREAD

**Issue by Natedogwoooof** [ProdigyPNP/ProdigyMathGameHacking#202]
### Describe your issue

bi im 14 can i donate to kicksstart you on ur new coding adventure when i get money and bc I Loved PNP and if not good luck on coding iits a skill i wish i knew  :( whelp ill be moving on to Prodigy X bye.

### Date of submittion

??????????

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Thank you for asking!
If you're going to donate, please tell me when, I'll send you a link.
