### ISSUE TITLE
How do I use the GUI on chromebook

### ISSUE THREAD

**Issue by mungK11** [ProdigyPNP/ProdigyMathGameHacking#207]
### Describe your issue

When I use the bookmark method on chrombook where I copy the hack and I make a bookmark and make the URL: Javascript: (and then script) i click it in prodigy but it doesn't work

### Date of submittion

2/22/23

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
@mungK11 

Please see #201.
(ProdigyPNP has ended it's service).
