### ISSUE TITLE
ProdigyPNP is "outdated."

### ISSUE THREAD

**Issue by Bruceq105** [ProdigyPNP/ProdigyMathGameHacking#211]
### Describe the bug

This always happens every time I go to Prodigy. Claims to be outdated.

![Capture 5](https://github.com/ProdigyPNP/ProdigyMathGameHacking/assets/134328829/fd43ca41-6b96-48ec-85fb-17a0ad942666)

![Capture 6](https://github.com/ProdigyPNP/ProdigyMathGameHacking/assets/134328829/02d9eef2-b1fb-48d4-a5ec-61a85896caad)

![Capture 7](https://github.com/ProdigyPNP/ProdigyMathGameHacking/assets/134328829/9a918e55-1389-4720-81c2-af1a82f83ee2)

Currently, ProdigyX is the only working cheat menu that works. Please fix the issue so I can use ProdigyPNP.

### Describe how to replicate bug

Inspect the pictures-this shwoed up when I was trying to  open Prodigy with ProdigyPNP.
![Capture 5](https://github.com/ProdigyPNP/ProdigyMathGameHacking/assets/134328829/285b8242-2d33-44e5-ab1b-2e37cbefe3d3)
![Capture 6](https://github.com/ProdigyPNP/ProdigyMathGameHacking/assets/134328829/47af575e-aed1-4448-bf90-75aff7ff1f60)
![Capture 7](https://github.com/ProdigyPNP/ProdigyMathGameHacking/assets/134328829/3c8bfe9c-9d24-45d6-be5c-309b491c5d31)

### Date of submittion

05/22/2023

### Your PHEx version

3.0.1

### Your operating system and the version

Microsoft Windows Pro 10 22H2

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Please read #201
