### ISSUE TITLE
[O] the chrome web store link is a 404

### ISSUE THREAD

**Issue by Acht-the-Deadf1sh** [ProdigyPNP/ProdigyMathGameHacking#221]
### Describe your issue

It's a 404

### Date of submittion

Nov 6th 2023

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
See #201
