### ISSUE TITLE
Prodigy X no longer works.

### ISSUE THREAD

**Issue by XPMUser** [ProdigyPNP/ProdigyMathGameHacking#223]
### Describe the bug

Prodigy X was taken down by Prodigy Education.

### Describe how to replicate bug

Ask Prodigy X to remake Prodigy X

### Date of submittion

12/9/2023

### Your PHEx version

Unknown

### Your operating system and the version

Windows 11 and 6-XXX-X

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
this isn't prodigy x my dawg, we aint affiliated or anything

**Comment by HIHIHIHIHIHIHIHI-ui** [comment]
huh?

**Comment by HIHIHIHIHIHIHIHI-ui** [comment]
...
