### ISSUE TITLE
[BUG] I got banned 

### ISSUE THREAD

**Issue by Gehshsj** [ProdigyPNP/ProdigyMathGameHacking#32]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by afkvido** [comment]
@Gehshsj Wdym "I got banned"


If you're getting a 418 and inactivity kick when you join Prodigy, use the hack "Close All popups"

**Comment by afkvido** [comment]
Don't click the "Log Out" buttons on the popups, just use the hack "Close All popups"

**Comment by afkvido** [comment]
Any questions?
