### ISSUE TITLE
PHEx MV3

### ISSUE THREAD

**Issue by prodigyhacker-2023** [ProdigyPNP/ProdigyMathGameHacking#50]
### Describe your issue

Manifest version 2 is deprecated, and support will be removed soon. See https://developer.chrome.com/blog/mv2-transition/ for more details. pls update to manifest V3.

### Date of submittion

Sat. May 27th

### Before submitting an issue

- [x] #51
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
PHEx is still usable until like 2026 or smth

**Comment by prodigyhacker-2023** [comment]
you gotta change the manifest file from v2 to v3

**Comment by afkvido** [comment]
@prodigyhacker-2023 

It isn't that simple. Our extension relies on some MV2 Extension features, which aren't supported in V3.

**Comment by afkvido** [comment]
Alr
