### ISSUE TITLE
battle hacks

### ISSUE THREAD

**Issue by aestheify** [ProdigyPNP/ProdigyMathGameHacking#52]
### Describe your issue

The health hacks wont work

### Date of submittion

5/29/2022

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
**It's pretty clear that you're new to the hub.** _(also your account is 6 hours old)_

Issues submitted to not only our, but _any_ repositories should be descriptive enough for us to understand. If we're not given a good description of the issue, then we don't understand what you want.
