### ISSUE TITLE
Won't get passed the loading screen

### ISSUE THREAD

**Issue by Username1Name2356PowerDokeySokey** [ProdigyPNP/ProdigyMathGameHacking#54]
### Describe the bug

So I did all the steps in your Discord. Logged in and went to Prodigy. But when it was loading. It was stuck halfway. And it wouldn't let me pass the loading screen.
Proof: 
https://www.awesomescreenshot.com/video/9203118

### Describe how to replicate bug

IDK

### Date of submittion

5/31/22

### Your PHEx version

2.19

### Your operating system and the version

idk

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
This isn't happening to me... Are you sure that this isn't fixed?
Please clear your cache, reload Prodigy, and try again.

If it still isn't working, reopen this issue.
