### ISSUE TITLE
[B] Remove item hack doesn't work

### ISSUE THREAD

**Issue by hellonearth311** [ProdigyPNP/ProdigyMathGameHacking#55]
### Describe the bug

Remove item hack doesn't work.

### Describe how to replicate bug

Open the menu, press remove item, and try to remove anything. It doesn't work.

### Date of submittion

6/6/22

### Your PHEx version

2.1.9

### Your operating system and the version

Windows 11

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [x] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Please submit a screen recording so I can see.

**Comment by hellonearth311** [comment]
Closing because it started working now even though I tried multiple times yesterday.

**Comment by afkvido** [comment]
This was a false report.
