### ISSUE TITLE
[HR] Parent Permission Giver

### ISSUE THREAD

**Issue by hellonearth311** [ProdigyPNP/ProdigyMathGameHacking#56]
### Describe the hack

A hack that automatically gives the email permission that prodigy forces you to get.

### Date of submittion

6/6/22

**Comment by Erisfiregamer1** [comment]
**Cannot be implemented!**
Reason:
This is a Prodigy server-side thing. We can't modify the data without access to their internal servers, which we do not have.
Sorry :(

**Comment by afkvido** [comment]
Hold up.... This is still possible! How about a wrapper that opens 10minutemail, and does something?

We're not done yet...

**Comment by Erisfiregamer1** [comment]
You missed a critical fact- What if Prodigy sends a new confirmation email in the future? That could be troublesome...
(I'd allow usage of an Eris Webservers subdomain to do this and allow reverification in the future)

**Comment by afkvido** [comment]
We can use Eris Webservers then :)

**Comment by afkvido** [comment]
Thanks!

**Comment by Erisfiregamer1** [comment]
Here's my idea.
- Extension sends a parent permission request email to "pnp@erisws.com", the email I allowed usage of
- Outside server checks every 5 minutes to see if there's any new parent permission requests at the email
- If there is, click and allow :trollface:

**Comment by afkvido** [comment]
Perfect!

**Comment by afkvido** [comment]
Any progress on this? @Erisfiregamer1

**Comment by Erisfiregamer1** [comment]
The email :b:roke so I can't help. Plus, I cannot code.

**Comment by afkvido** [comment]
> The email 🅱️roke so I can't help

unfortunate.

**Comment by afkvido** [comment]
> Plus, I cannot code.

wdym

**Comment by Erisfiregamer1** [comment]
> > Plus, I cannot code.
> 
> wdym

By "cannot code" I mean I can only *read* the code PHEx is made up of and modify SOME of it from my limited knowledge. Making hacks is WAY out of that scope.

**Comment by afkvido** [comment]
damn bro. if smth is unclear in the code, just ask me, i know most things OTHER THAN `util.ts` in P-NP.

**Comment by afkvido** [comment]
Maybe it's possible to do this by modifying the player object, and no emails will be needed. Sorry Eris, your're useless now.
